-- CreateTable
CREATE TABLE "products" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "image" STRING NOT NULL,
    "title" STRING NOT NULL,
    "stars" INT4,
    "description" STRING,
    "startedreading" STRING,
    "endedreading" STRING,
    "genre_id" INT4,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "products_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "genres" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,

    CONSTRAINT "genres_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "product_genres" (
    "productId" INT4 NOT NULL,
    "genreId" INT4 NOT NULL,

    CONSTRAINT "product_genres_pkey" PRIMARY KEY ("productId","genreId")
);

-- CreateTable
CREATE TABLE "users" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" STRING NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "first_name" STRING NOT NULL,
    "last_name" STRING NOT NULL,
    "password_hash" STRING NOT NULL,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- AddForeignKey
ALTER TABLE "product_genres" ADD CONSTRAINT "product_genres_productId_fkey" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_genres" ADD CONSTRAINT "product_genres_genreId_fkey" FOREIGN KEY ("genreId") REFERENCES "genres"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
